
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 29;
  public static final int PCI = 25;
  public static final int LIT_REAL = 10;
  public static final int RESTA = 14;
  public static final int CAP = 49;
  public static final int LIT_CAD = 11;
  public static final int FIN = 52;
  public static final int REFERENCIA = 48;
  public static final int WRITE = 43;
  public static final int DELETE = 41;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int IGUAL = 22;
  public static final int TYPE = 45;
  public static final int LLAP = 32;
  public static final int EVAL = 28;
  public static final int OR = 7;
  public static final int BOOL = 2;
  public static final int CALL = 46;
  public static final int DIV = 16;
  public static final int SUMA = 13;
  public static final int IF = 36;
  public static final int MAY_IGUAL = 21;
  public static final int EOF = 0;
  public static final int ASIG = 23;
  public static final int TRUE = 30;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int COMA = 26;
  public static final int LIT_ENT = 9;
  public static final int NULL = 34;
  public static final int MENOR = 18;
  public static final int MOD = 17;
  public static final int CCI = 50;
  public static final int PCOMA = 27;
  public static final int REAL = 4;
  public static final int MAYOR = 19;
  public static final int ENT = 3;
  public static final int INDIRECCION = 47;
  public static final int PAP = 24;
  public static final int ELSE = 37;
  public static final int PUNTO = 51;
  public static final int MEN_IGUAL = 20;
  public static final int NL = 44;
  public static final int READ = 42;
  public static final int IDEN = 12;
  public static final int WHILE = 38;
  public static final int LLCI = 33;
  public static final int PROC = 35;
  public static final int STRING = 5;
  public static final int FALSE = 31;
  public static final int STRUCT = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "ENT",
  "REAL",
  "STRING",
  "AND",
  "OR",
  "NOT",
  "LIT_ENT",
  "LIT_REAL",
  "LIT_CAD",
  "IDEN",
  "SUMA",
  "RESTA",
  "MUL",
  "DIV",
  "MOD",
  "MENOR",
  "MAYOR",
  "MEN_IGUAL",
  "MAY_IGUAL",
  "IGUAL",
  "ASIG",
  "PAP",
  "PCI",
  "COMA",
  "PCOMA",
  "EVAL",
  "DISTINTO",
  "TRUE",
  "FALSE",
  "LLAP",
  "LLCI",
  "NULL",
  "PROC",
  "IF",
  "ELSE",
  "WHILE",
  "STRUCT",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "TYPE",
  "CALL",
  "INDIRECCION",
  "REFERENCIA",
  "CAP",
  "CCI",
  "PUNTO",
  "FIN"
  };
}

