package tiny;

public enum ClaseLexica {
	BOOL, ENT, REAL,STRING, AND, OR, NOT, LIT_BOOL, LIT_ENT, LIT_REAL,LIT_CAD,
	IDEN, SUMA, RESTA, MUL, DIV,MOD, MENOR, MAYOR, MEN_IGUAL, MAY_IGUAL, 
	IGUAL, ASIG,PAP,PCI,COMA, PCOMA,EVAL, EOF, DISTINTO,TRUE,FALSE,LLAP,LLCI,
	EXP0,NULL,PROC,IF,ELSE,WHILE,STRUCT,NEW,DELETE,READ,WRITE,NL,TYPE,CALL,INDIRECCION,REFERENCIA,
	CAP,CCI,PUNTO,FIN
}
