package tiny0;

public enum ClaseLexica {
 BOOL, ENT, REAL, AND, OR, NOT, LIT_BOOL, LIT_ENT, LIT_REAL,
 IDEN, SUMA, RESTA, MULT, DIV, MENOR, MAYOR, MEN_IGUAL, MAY_IGUAL, 
 IGUAL, ASIG,PAP,PCIERRE,COMA, PCOMA,ARROBA, EOF, DISTINTO
}